"""
Context & Security Intelligence Engine (Phase 2.3)
---------------------------------------------------
Deterministic, explainable, rule-based security engine combining:
- Person recognition (Identity, Authorization status, Role)
- Object detection (Protected objects, Spatial proximity)
- Virtual surveillance zones (Normal, Restricted, Protected Asset Area)
- Operational time windows (Authorized hours)

Produces structured, human-readable SecurityDecisions with traceable rationale.
"""

from dataclasses import dataclass, field
from datetime import datetime, time as dtime
import json
import logging
import math
from typing import Any, Dict, List, Optional, Tuple

import cv2
import numpy as np

from config import (
    PROTECTED_OBJECT_CLASSES,
    DEFAULT_ZONES,
    AUTHORIZED_HOURS_START,
    AUTHORIZED_HOURS_END,
    PROXIMITY_PIXEL_THRESHOLD,
    CONTEXT_ALERT_COOLDOWN_SECONDS,
)
from src.events.event_types import RiskLevel, EventType
from src.core.policy_engine import PolicyEngine, ExplainableDecisionTuple, PolicyEvaluationResult, ZonePolicy
from src.core.track_security_state import TrackSecurityStateManager, TrackSecurityState
from src.core.incident_manager import IncidentManager, SecurityIncident
from src.core.person_entity import PersonEntity, PersonEntityFusionEngine
from src.core.security_analytics import SecurityAnalyticsEngine

logger = logging.getLogger("WatchGuardVision.ContextEngine")


@dataclass
class SecurityDecision:
    """Structured security assessment generated by ContextEngine."""
    risk_level: RiskLevel
    decision: str
    reason: str
    matched_rules: List[str] = field(default_factory=list)
    evidence_required: bool = False
    recommended_response: str = "Standard surveillance monitoring."
    is_access_granted: bool = True
    correlated_interactions: List[Dict[str, Any]] = field(default_factory=list)
    context_summary: Dict[str, Any] = field(default_factory=dict)
    event_type: EventType = EventType.SECURITY_ALERT
    explainable_tuple: Optional[ExplainableDecisionTuple] = None
    incident: Optional[SecurityIncident] = None
    per_track_states: List[Dict[str, Any]] = field(default_factory=list)
    person_entities: List[Dict[str, Any]] = field(default_factory=list)
    ccsdf_result: Optional[Dict[str, Any]] = None

    @property
    def access_state(self) -> str:
        return "GRANTED" if self.is_access_granted else "DENIED"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "risk_level": self.risk_level.value,
            "decision": self.decision,
            "reason": self.reason,
            "matched_rules": self.matched_rules,
            "evidence_required": self.evidence_required,
            "recommended_response": self.recommended_response,
            "is_access_granted": self.is_access_granted,
            "access_state": self.access_state,
            "correlated_interactions": self.correlated_interactions,
            "context_summary": self.context_summary,
            "event_type": self.event_type.value,
            "explainable_tuple": self.explainable_tuple.to_dict() if self.explainable_tuple else None,
            "incident": self.incident.to_dict() if self.incident else None,
            "per_track_states": self.per_track_states,
            "person_entities": self.person_entities,
            "ccsdf_result": self.ccsdf_result,
        }


def compute_box_distance(bbox1: Tuple[int, int, int, int], bbox2: Tuple[int, int, int, int]) -> float:
    """
    Calculates the edge-to-edge distance in pixels between two bounding boxes (x, y, w, h).
    Returns 0.0 if they overlap or touch.
    """
    x1, y1, w1, h1 = bbox1
    x2, y2, w2, h2 = bbox2
    r1, b1 = x1 + w1, y1 + h1
    r2, b2 = x2 + w2, y2 + h2

    # Horizontal edge distance
    if r1 < x2:
        dx = float(x2 - r1)
    elif r2 < x1:
        dx = float(x1 - r2)
    else:
        dx = 0.0

    # Vertical edge distance
    if b1 < y2:
        dy = float(y2 - b1)
    elif b2 < y1:
        dy = float(y1 - b2)
    else:
        dy = 0.0

    return math.hypot(dx, dy)


class ContextEngine:
    """
    Core rule-based, explainable Security Context Engine for WatchGuard Vision.
    Correlates identities, objects, locations, and time to determine risk posture.
    """

    def __init__(
        self,
        protected_objects: Optional[List[str]] = None,
        zones_config: Optional[Dict[str, Dict[str, Any]]] = None,
        hours_start: str = AUTHORIZED_HOURS_START,
        hours_end: str = AUTHORIZED_HOURS_END,
        proximity_threshold: float = PROXIMITY_PIXEL_THRESHOLD,
        db_manager = None,
    ):
        self.protected_objects = list(protected_objects or PROTECTED_OBJECT_CLASSES)
        self.zones_config = dict(zones_config or DEFAULT_ZONES)
        self.hours_start = hours_start
        self.hours_end = hours_end
        self.proximity_threshold = proximity_threshold
        self.db_manager = db_manager

        # Phase 4 Temporal Policy & Incident Engines
        self.policy_engine = PolicyEngine()
        self.track_manager = TrackSecurityStateManager()
        self.incident_manager = IncidentManager(db_manager=db_manager)
        self.fusion_engine = PersonEntityFusionEngine(proximity_threshold_pixels=self.proximity_threshold)

        # Phase 5 Security Analytics Engine
        self.security_analytics = SecurityAnalyticsEngine(
            db_manager=db_manager,
            context_engine=self,
            incident_manager=self.incident_manager,
        )

        self._alert_cooldowns: Dict[str, float] = {}
        self._last_decision: Optional[SecurityDecision] = None
        self._simulated_time_override: Optional[dtime] = None
        self._active_zone_override: Optional[str] = None
        self.scene_generation: int = 0
        self._last_scene_signature: Optional[Tuple[Any, ...]] = None

        # Phase 5.16 & 5.20: CCSDF, Tailgating, and Behavioral Anomaly Research Engines
        try:
            from src.research.ccsdf_engine import CCSDFEngine
            from src.research.tailgating_engine import TailgatingDetector
            from src.research.behavior_engine import BehaviorAnomalyEngine
            self.ccsdf_engine: Optional[CCSDFEngine] = CCSDFEngine()
            self.tailgating_detector: Optional[TailgatingDetector] = TailgatingDetector()
            self.behavior_engine: Optional[BehaviorAnomalyEngine] = BehaviorAnomalyEngine()
        except ImportError:
            self.ccsdf_engine = None
            self.tailgating_detector = None
            self.behavior_engine = None

    @property
    def last_decision(self) -> Optional[SecurityDecision]:
        return self._last_decision

    @last_decision.setter
    def last_decision(self, decision: Optional[SecurityDecision]) -> None:
        self._last_decision = decision

    def set_time_override(self, time_override: Optional[dtime]) -> None:
        """Sets a simulated time override (e.g. 21:30 for after-hours testing)."""
        self._simulated_time_override = time_override

    def set_zone_override(self, zone_name: Optional[str]) -> None:
        """Sets a manual zone override for testing (e.g. 'RESTRICTED')."""
        self._active_zone_override = zone_name

    def is_authorized_time(self, current_dt: Optional[datetime] = None) -> Tuple[bool, str]:
        """
        Checks whether the current/provided time falls within authorized hours.
        Returns: (is_auth, time_str)
        """
        if self._simulated_time_override is not None:
            t = self._simulated_time_override
        else:
            now = current_dt or datetime.now()
            t = now.time()

        time_str = t.strftime("%H:%M")
        try:
            start_parts = [int(p) for p in self.hours_start.split(":")]
            end_parts = [int(p) for p in self.hours_end.split(":")]
            t_start = dtime(start_parts[0], start_parts[1])
            t_end = dtime(end_parts[0], end_parts[1])

            if t_start <= t_end:
                is_auth = t_start <= t <= t_end
            else:
                # Overnight window (e.g. 22:00 to 06:00)
                is_auth = t >= t_start or t <= t_end
            return is_auth, time_str
        except Exception as e:
            logger.error(f"Error checking authorized time window: {e}")
            return True, time_str

    def determine_zone(
        self,
        person_bbox: Optional[Tuple[int, int, int, int]],
        frame_shape: Tuple[int, int],
    ) -> str:
        """
        Determines which surveillance zone a person's bounding box occupies.
        """
        if self._active_zone_override is not None:
            return self._active_zone_override

        if person_bbox is None:
            return "NORMAL"

        h_frame, w_frame = frame_shape[:2]
        if w_frame <= 0 or h_frame <= 0:
            return "NORMAL"

        px, py, pw, ph = person_bbox
        # Center point of person bounding box
        pcx = px + pw * 0.5
        pcy = py + ph * 0.5

        # Check RESTRICTED zone first
        for z_key in ["RESTRICTED", "PROTECTED_ASSET_AREA"]:
            if z_key not in self.zones_config:
                continue
            z_info = self.zones_config[z_key]
            rx_n, ry_n, rw_n, rh_n = z_info["rect_norm"]
            zx1 = rx_n * w_frame
            zy1 = ry_n * h_frame
            zx2 = (rx_n + rw_n) * w_frame
            zy2 = (ry_n + rh_n) * h_frame

            if zx1 <= pcx <= zx2 and zy1 <= pcy <= zy2:
                return z_key

        return "NORMAL"

    def find_spatial_interactions(
        self,
        person_bbox: Optional[Tuple[int, int, int, int]],
        objects: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """
        Finds objects in close visual proximity / interaction candidate range with a person.
        """
        if person_bbox is None or not objects:
            return []

        interactions: List[Dict[str, Any]] = []
        for obj in objects:
            lbl = obj.get("label", "")
            if lbl == "person":
                continue
            obj_bbox = obj.get("bbox", (0, 0, 0, 0))
            dist = compute_box_distance(person_bbox, obj_bbox)
            is_near = dist <= self.proximity_threshold
            is_protected = lbl in self.protected_objects

            if is_near or is_protected:
                interactions.append({
                    "object_label": lbl,
                    "confidence": obj.get("confidence", 0.0),
                    "distance_pixels": round(dist, 1),
                    "is_in_proximity": is_near,
                    "is_protected": is_protected,
                    "object_bbox": obj_bbox,
                })

        return interactions

    def evaluate_context(
        self,
        person_data: Dict[str, Any],
        object_data: Dict[str, Any],
        camera_id: int = 0,
        frame_shape: Tuple[int, int] = (480, 640),
        current_dt: Optional[datetime] = None,
    ) -> SecurityDecision:
        """
        Evaluates active vision streams against deterministic security rules.

        Returns:
            SecurityDecision with risk level, decision code, human-readable reason, and actions.
        """
        has_person = person_data.get("detected", False)
        has_unknown = person_data.get("has_unknown", False)
        has_authorized = person_data.get("has_authorized", False)
        has_verifying = person_data.get("has_verifying", False)
        has_spoof = person_data.get("has_spoof", False)
        people = person_data.get("people", [])
        primary_person = people[0] if people else None
        person_name = primary_person.get("name", "Unknown Person") if primary_person else None
        person_bbox = primary_person.get("bbox") if primary_person else None

        detected_objects = object_data.get("objects", [])
        object_summary = object_data.get("summary", "None")

        # 0. Multi-Modal Person Entity Fusion (Phase 4.2)
        entities, non_person_objects, clean_obj_summary = self.fusion_engine.fuse(
            people=people,
            detected_objects=detected_objects,
            zones_config=self.zones_config,
        )

        # 1. Evaluate Environmental & Spatial Context
        zone = self.determine_zone(person_bbox, frame_shape)
        is_auth_time, time_str = self.is_authorized_time(current_dt)
        interactions = self.find_spatial_interactions(person_bbox, detected_objects)

        # Filter interactions specifically for protected objects within proximity
        protected_interactions = [
            i for i in interactions if i["is_protected"] and i["is_in_proximity"]
        ]

        has_spoof = person_data.get("has_spoof", False)
        is_primary_known = bool(primary_person.get("is_known", False)) if primary_person else False
        is_primary_spoof = bool(primary_person.get("is_spoof", False)) if primary_person else False

        primary_track_id = primary_person.get("track_id", 1) if primary_person else None
        primary_track_state = self.track_manager.get_track(primary_track_id) if primary_track_id else None

        context_summary = {
            "person_detected": has_person or len(entities) > 0,
            "person_name": person_name or "None",
            "is_authorized": has_authorized,
            "is_unknown": has_unknown,
            "has_spoof": has_spoof,
            "objects_detected": len(non_person_objects),
            "object_summary": clean_obj_summary,
            "objects": non_person_objects,
            "person_entities": [e.to_dict() for e in entities],
            "person_entity_count": len(entities),
            "zone": zone,
            "zone_name": self.zones_config.get(zone, {}).get("name", zone),
            "time_str": time_str,
            "is_authorized_hours": is_auth_time,
            "camera_id": camera_id,
        }

        track_states_list: List[Dict[str, Any]] = []
        track_eval_results: List[PolicyEvaluationResult] = []

        # 2. Per-Track Evaluation & Isolation (Phase 4)
        if people:
            for p in people:
                tid = p.get("track_id", 1)
                p_name = p.get("name", "Unknown Person")
                p_sim = float(p.get("similarity", 0.0))
                p_conf = float(p.get("confidence", 0.0))
                p_known = bool(p.get("is_known", False))
                p_role = p.get("role", "Staff" if p_known else "Visitor")
                p_spoof = bool(p.get("is_spoof", False))
                p_atk = p.get("attack_type", "PRESENTATION_ATTACK" if p_spoof else None)
                p_live_conf = float(p.get("liveness_confidence", 0.90 if not p_spoof else 0.10))

                pad_res = p.get("pad_result")
                joint_dec = p.get("joint_decision")

                p_live_state = "LIVE"
                if p_spoof:
                    p_live_state = "SPOOF"
                elif has_verifying or p.get("is_verifying", False) or (pad_res and pad_res.metadata.get("warmup_active", False)) or (joint_dec and getattr(joint_dec.status, "value", "") == "LIVENESS_VERIFYING"):
                    p_live_state = "WARMUP"
                elif pad_res:
                    if pad_res.is_live:
                        p_live_state = "LIVE"
                    else:
                        p_live_state = "SPOOF"

                p_bbox = p.get("bbox")
                p_zone = self.determine_zone(p_bbox, frame_shape)
                p_zone_name = self.zones_config.get(p_zone, {}).get("name", p_zone)

                p_interactions = self.find_spatial_interactions(p_bbox, detected_objects)
                p_prot_interactions = [i for i in p_interactions if i["is_protected"] and i["is_in_proximity"]]

                # Policy Evaluation via PolicyEngine
                pol_res = self.policy_engine.evaluate(
                    identity=p_name,
                    role=p_role,
                    is_known=p_known,
                    liveness_state=p_live_state,
                    liveness_conf=p_live_conf,
                    zone_id=p_zone,
                    time_str=time_str,
                    is_auth_time=is_auth_time,
                    nearby_objects=p_prot_interactions,
                    is_spoof=p_spoof,
                    attack_type=p_atk,
                )

                # Update Isolated Track State
                t_state = self.track_manager.get_or_create_track(tid)
                transition_info = t_state.update(
                    identity=p_name,
                    identity_conf=p_sim if p_known else p_conf,
                    role=p_role,
                    is_known=p_known,
                    liveness_state=p_live_state,
                    liveness_conf=p_live_conf,
                    is_spoof=p_spoof,
                    attack_type=p_atk,
                    zone_id=p_zone,
                    zone_name=p_zone_name,
                    time_str=time_str,
                    is_auth_time=is_auth_time,
                    nearby_objects=p_prot_interactions,
                    policy_code=pol_res.policy_code,
                    is_access_granted=pol_res.is_access_granted,
                    risk_level=pol_res.risk_level,
                    reason=pol_res.reason,
                )

                # Handle Zone Exit (Close associated active incident)
                if transition_info.get("is_exit") and transition_info.get("closed_incident_id"):
                    self.incident_manager.close_incident(
                        transition_info["closed_incident_id"],
                        reason=f"Subject {p_name} exited {p_zone_name}",
                    )

                # Repeated Violation Escalation Check (Phase 4.1)
                escalation = t_state.check_repeated_violations_escalation()
                if escalation:
                    esc_risk, esc_code, esc_reason = escalation
                    pol_res.risk_level = esc_risk
                    pol_res.policy_code = esc_code
                    pol_res.reason = esc_reason
                    pol_res.explainable_tuple.result = f"ACCESS DENIED (ESCALATED) | Risk: {esc_risk.value} | Decision: {esc_code}"
                # Synchronize fused PersonEntity with post-policy evaluated track state
                for ent in entities:
                    if ent.track_id == tid:
                        ent.access_state = t_state.access_state
                        ent.decision_code = pol_res.policy_code
                        ent.reason = pol_res.reason
                        ent.risk_level = pol_res.risk_level
                        ent.zone = p_zone
                        ent.zone_name = p_zone_name

                track_states_list.append(t_state.to_dict())
                track_eval_results.append(pol_res)

        # 3. Overall Frame Decision Aggregation (Highest Risk Precedence: RED -> ORANGE -> YELLOW -> GREEN)
        if track_eval_results:
            risk_rank = {RiskLevel.RED: 3, RiskLevel.ORANGE: 2, RiskLevel.YELLOW: 1, RiskLevel.GREEN: 0}
            top_eval = max(track_eval_results, key=lambda r: risk_rank.get(r.risk_level, 0))

            # Synchronize context_summary with post-policy authoritative entities
            context_summary["person_entities"] = [e.to_dict() for e in entities]

            decision = SecurityDecision(
                risk_level=top_eval.risk_level,
                decision=top_eval.policy_code,
                reason=top_eval.reason,
                matched_rules=top_eval.matched_rules,
                evidence_required=top_eval.evidence_required,
                recommended_response=top_eval.recommended_action,
                is_access_granted=top_eval.is_access_granted,
                correlated_interactions=interactions,
                context_summary=context_summary,
                event_type=top_eval.event_type,
                explainable_tuple=top_eval.explainable_tuple,
                per_track_states=track_states_list,
                person_entities=[e.to_dict() for e in entities],
            )
        else:
            # Empty Perimeter / Routine Monitoring
            clean_eval = self.policy_engine.evaluate(
                identity="None",
                role="None",
                is_known=False,
                liveness_state="LIVE",
                liveness_conf=1.0,
                zone_id=zone,
                time_str=time_str,
                is_auth_time=is_auth_time,
                nearby_objects=[],
                is_spoof=False,
            )
            decision = SecurityDecision(
                risk_level=RiskLevel.GREEN,
                decision="NORMAL_ACTIVITY",
                reason=clean_eval.reason,
                matched_rules=clean_eval.matched_rules,
                evidence_required=False,
                recommended_response=clean_eval.recommended_action,
                is_access_granted=False,
                correlated_interactions=interactions,
                context_summary=context_summary,
                event_type=clean_eval.event_type,
                explainable_tuple=clean_eval.explainable_tuple,
                per_track_states=[],
                person_entities=[e.to_dict() for e in entities],
            )

        # 4. Incident Lifecycle Dispatching (Phase 4.1 Debounced)
        if decision.risk_level in (RiskLevel.ORANGE, RiskLevel.RED):
            primary_track_id = primary_person.get("track_id", 1) if primary_person else None
            primary_track_state = self.track_manager.get_track(primary_track_id) if primary_track_id else None

            active_inc_id = None
            duration_s = 0.0
            if primary_track_state:
                active_inc_id = primary_track_state.active_zone_incident_id or primary_track_state.active_spoof_incident_id
                duration_s = primary_track_state.duration_inside_zone_seconds

            incident = self.incident_manager.process_incident(
                risk_level=decision.risk_level,
                policy_code=decision.decision,
                reason=decision.reason,
                zone_name=context_summary.get("zone_name", "Standard Perimeter"),
                person_name=person_name if person_name != "None" else None,
                track_id=primary_track_id,
                identity_confidence=float(primary_person.get("similarity", 0.0)) if primary_person else 0.0,
                liveness_state="SPOOF" if has_spoof else "LIVE",
                liveness_confidence=float(primary_person.get("liveness_confidence", 0.90)) if primary_person else 0.0,
                time_status="PERMITTED_HOURS" if is_auth_time else "AFTER_HOURS",
                nearby_objects=[o.get("object_label", "object") for o in protected_interactions],
                duration_seconds=duration_s,
                active_incident_id=active_inc_id,
            )
            decision.incident = incident
            if primary_track_state and incident:
                if has_spoof:
                    primary_track_state.active_spoof_incident_id = incident.incident_id
                else:
                    primary_track_state.active_zone_incident_id = incident.incident_id

        # Scene signature & generation tracking for live state consistency (Phase 5.11)
        scene_sig = (
            len(entities),
            tuple(sorted(getattr(e, "identity", "Unknown") for e in entities)),
            tuple(sorted(getattr(e, "access_state", "UNKNOWN") for e in entities)),
            len(non_person_objects),
            tuple(sorted(o.get("label", "") for o in non_person_objects)),
            zone,
            decision.risk_level.value,
        )
        if scene_sig != self._last_scene_signature:
            self.scene_generation += 1
            self._last_scene_signature = scene_sig

        # Phase 5.20: Tailgating & Behavioral Anomaly Evaluation
        s_beh = 0.0
        beh_status = "NORMAL_ACTIVITY"
        is_tailgating = False
        s_tail = 0.0
        tail_status = "NONE"
        tail_conf = 0.0
        foll_ident = None
        auth_ident = None
        tail_dist = 999.0

        if getattr(self, "tailgating_detector", None) is not None and len(entities) >= 2:
            entities_dicts = [
                {
                    "track_id": getattr(e, "track_id", idx + 1),
                    "identity": getattr(e, "name", getattr(e, "identity", "Unknown Person")),
                    "is_known": getattr(e, "is_known", False),
                    "access_state": getattr(e, "access_state", "PENDING"),
                    "liveness_state": getattr(e, "liveness_state", "LIVE"),
                    "bbox": getattr(e, "bbox", (0, 0, 0, 0)),
                    "zone": zone,
                }
                for idx, e in enumerate(entities)
            ]
            tail_events, s_tail = self.tailgating_detector.evaluate_tracks(entities_dicts)
            if tail_events:
                is_tailgating = True
                tail_status = "TAILGATING_SUSPECTED"
                first_tail = tail_events[0]
                tail_conf = first_tail.confidence
                foll_ident = first_tail.follower_identity
                auth_ident = first_tail.authorized_identity
                tail_dist = first_tail.spatial_distance

        if getattr(self, "behavior_engine", None) is not None and primary_person:
            tid = primary_person.get("track_id", 1)
            p_ident = primary_person.get("name", "Unknown Person")
            p_known = primary_person.get("is_known", False)
            nearest_dist = 999.0
            if protected_interactions:
                nearest_dist = float(protected_interactions[0].get("distance_pixels", 50.0))
            is_viol = ("DENIED" in decision.access_state or decision.risk_level.value in ("RED", "ORANGE"))
            s_beh, beh_status, _ = self.behavior_engine.update_track_observation(
                track_id=tid,
                identity=p_ident,
                is_known=p_known,
                zone=zone,
                is_after_hours=not is_auth_time,
                nearest_asset_dist=nearest_dist,
                is_violation=is_viol,
            )

        context_summary["s_behavior"] = s_beh
        context_summary["behavior_status"] = beh_status
        context_summary["is_tailgating_suspected"] = is_tailgating
        context_summary["s_tailgating"] = s_tail
        context_summary["tailgating_status"] = tail_status
        context_summary["tailgating_confidence"] = tail_conf
        context_summary["follower_identity"] = foll_ident
        context_summary["authorized_identity"] = auth_ident
        context_summary["tailgating_distance"] = tail_dist

        # Phase 5.16 & 5.20: Non-intrusive CCSDF Research Evaluation Layer
        if getattr(self, "ccsdf_engine", None) is not None:
            try:
                ccsdf_eval = self.ccsdf_engine.evaluate_decision_context(
                    decision=decision,
                    primary_person=primary_person,
                    primary_track_state=primary_track_state,
                    context_summary=context_summary,
                    protected_interactions=protected_interactions,
                    is_auth_time=is_auth_time,
                    time_str=time_str,
                )
                decision.ccsdf_result = ccsdf_eval.to_dict()
            except Exception as e:
                logger.debug(f"CCSDF evaluation skipped: {e}")

        self._last_decision = decision
        return decision

    def should_trigger_alert(
        self,
        rule_key: str,
        cooldown_seconds: float = CONTEXT_ALERT_COOLDOWN_SECONDS,
    ) -> bool:
        """
        Thread-safe cooldown check to prevent event/evidence flooding.
        """
        now = datetime.now().timestamp()
        last_time = self._alert_cooldowns.get(rule_key, 0.0)
        if now - last_time >= cooldown_seconds:
            self._alert_cooldowns[rule_key] = now
            return True
        return False

    def draw_context_hud(
        self,
        frame: np.ndarray,
        decision: SecurityDecision,
        show_zones: bool = True,
        show_interaction_lines: bool = True,
    ) -> np.ndarray:
        """
        Draws virtual zone boundaries and interaction correlation vectors onto frame.
        """
        if frame is None or frame.size == 0:
            return frame

        annotated = frame.copy()
        h, w = frame.shape[:2]

        # 1. Draw Virtual Surveillance Zones
        if show_zones and "RESTRICTED" in self.zones_config:
            z_info = self.zones_config["RESTRICTED"]
            rx_n, ry_n, rw_n, rh_n = z_info["rect_norm"]
            zx1, zy1 = int(rx_n * w), int(ry_n * h)
            zx2, zy2 = int((rx_n + rw_n) * w), int((ry_n + rh_n) * h)

            # Zone tint
            overlay = annotated.copy()
            cv2.rectangle(overlay, (zx1, zy1), (zx2, zy2), (0, 0, 180), -1)
            cv2.addWeighted(overlay, 0.12, annotated, 0.88, 0, annotated)

            # Zone border
            cv2.rectangle(annotated, (zx1, zy1), (zx2, zy2), (0, 0, 220), 1)
            cv2.putText(
                annotated,
                "[ZONE: RESTRICTED AREA]",
                (zx1 + 10, zy1 + 25),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.45,
                (0, 100, 255),
                1,
                cv2.LINE_AA,
            )

        # 2. Draw Interaction Vectors between Person and Objects
        if show_interaction_lines and decision.correlated_interactions:
            person_bbox = decision.context_summary.get("person_name")
            for inter in decision.correlated_interactions:
                if not inter.get("is_in_proximity", False):
                    continue
                obj_bbox = inter.get("object_bbox")
                if not obj_bbox:
                    continue

                ox, oy, ow, oh = obj_bbox
                ocx, ocy = int(ox + ow * 0.5), int(oy + oh * 0.5)

                # Draw interaction vector line to frame center or person box
                # If target is protected, highlight in amber/red
                line_color = (0, 70, 255) if inter["is_protected"] else (255, 200, 0)
                dist_txt = f"{inter['object_label'].upper()} ({int(inter['distance_pixels'])}px)"

                cv2.circle(annotated, (ocx, ocy), 4, line_color, -1)
                cv2.putText(
                    annotated,
                    f"PROXIMITY: {dist_txt}",
                    (ox, oy + oh + 15),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.38,
                    line_color,
                    1,
                    cv2.LINE_AA,
                )

        return annotated
